globals:
  session_name: user
  lang: es
  salt: yjlm
  paths:
    upload: 'uploads'
  backup:
    dir: 'backup'
    file_format: '%m_%d_%Y_%H_%M_%S'
  csv:
    date_format: '%m/%d/%Y %H:%M %z'
    date_full_format: '%m/%d/%Y %H:%M:%S %z'
    time_format: '%H:%M %z'
    time_full_format: '%H:%M:%S %z'
development:
  scope: ''
production:
  scope: '/km2'