BEGIN;

ALTER TABLE countries 
  ADD COLUMN gini DOUBLE PRECISION,
  ADD COLUMN abbreviation VARCHAR(10)
;

ALTER TABLE cities
  ADD COLUMN future_population INTEGER
;

ALTER TABLE kms
  ADD COLUMN area_type VARCHAR(100),
  ADD COLUMN uff DOUBLE PRECISION,
  ADD COLUMN ucf DOUBLE PRECISION,
  ADD COLUMN one_way_streets INTEGER DEFAULT 0,
  ADD COLUMN two_way_streets INTEGER DEFAULT 0,
  ADD COLUMN speed DOUBLE PRECISION
;  

COMMIT;
